# Generated by Django 2.0.13 on 2019-04-08 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190408_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
