# Generated by Django 2.0.13 on 2019-04-08 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190408_2106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='_id',
            new_name='id',
        ),
    ]
