# Generated by Django 2.0.13 on 2019-04-08 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_product_technology_map_technology_map_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technology_map',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Product'),
        ),
        migrations.AlterField(
            model_name='technology_map_position',
            name='material_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Material'),
        ),
        migrations.AlterField(
            model_name='technology_map_position',
            name='technology_map_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Product'),
        ),
    ]
