# Generated by Django 2.2 on 2019-04-09 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20190408_2131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='technology_map',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='technology_map_position',
            old_name='material_id',
            new_name='material',
        ),
        migrations.RenameField(
            model_name='technology_map_position',
            old_name='technology_map_id',
            new_name='technology_map',
        ),
    ]
