# Generated by Django 2.2 on 2019-04-10 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20190409_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to='documents/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='someImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='H:\\_SSD\\Mega\\_8й семак\\СОВРЕМЕННЫЕ СРЕДСТВА ПРОМЫШЛЕННОЙ РАЗРАБОТКИ ПО\\untitled\\static')),
            ],
        ),
    ]
